# Generated by Django 3.0.4 on 2020-03-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.TextField(default='', max_length=150)),
                ('time', models.TextField(default='', max_length=150)),
                ('charging_level', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=150)),
                ('battery_voltage', models.CharField(max_length=150)),
                ('decreased_voltage', models.TextField(max_length=150)),
                ('charging_status', models.CharField(max_length=150)),
            ],
        ),
    ]
